#app settings

WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_TITLE = "Process checker"
VERSION = "1.0"


CONSOLE_HEIGHT = 100
CONSOLE_FONT = "Calibri 16"

VIZ_SIMULATION_TIMER = 1000
MAX_VISIBLE_GRAPH_NODES = 400